{% set name = "asciimatics" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4120461a3fb345638dee4fe0f8a3d3f9b6d2d2e003f95c5f914523f94463158d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - wcwidth
    - pyfiglet >=0.7.2
    - pillow >=2.7.0
    - future
    - pywin32  # [win]

test:
  imports:
    - asciimatics

about:
  home: http://github.com/peterbrittain/asciimatics
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Package to help people create full-screen text UIs

  description: |
    Asciimatics is a package to help people create full-screen text UIs 
    (from interactive forms to ASCII animations) on any platform. 
  doc_url: https://asciimatics.readthedocs.io/
  dev_url: http://github.com/peterbrittain/asciimatics

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
