{% set name = "asciimatics" %}
{% set version = "1.11.0" %}
{% set fn = "{}-{}-py2.py3-none-any.whl".format(name, version) %}
{% set sha256 = "6c7ad130a0663ecb1b3a731b82c51d6662f1d2c4760de2b8ffc9c1faba775360" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/py2.py3/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed {{ fn }}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - wcwidth
    - pyfiglet >=0.7.2
    - pillow >=2.7.0
    - future
    - pywin32  # [win]

test:
  imports:
    - asciimatics 

about:
  home: http://github.com/peterbrittain/asciimatics
  license: Apache-2.0
  license_family: Apache
  # https://github.com/peterbrittain/asciimatics/pull/151
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Package to help people create full-screen text UIs'

  description: |
    Asciimatics is a package to help people create full-screen text UIs 
    (from interactive forms to ASCII animations) on any platform. 
  doc_url: https://asciimatics.readthedocs.io/ 
  dev_url: http://github.com/peterbrittain/asciimatics

extra:
  recipe-maintainers:
    - CurtLH
