travis:
  secure:
    BINSTAR_TOKEN: Gi4R0foMwSVXziPpijwTFq1C2CwEZWIhIZ/9wUFKU7rTH5/WUNGDo0CbSNejqSgHmzY2gZ71EV3MdnOjEBS2t1X6P9AIlTnXAjXMOXtYGHXdOET4RMWTknERV6/bkjgJ1TdXvAmgq/3BGGZ8FwO4RXygMUnztEhSCr2wMFB2sGD4CylDmn/V31azoH3333NNPnt4aNiWLyiFJOHxWQzRzBqFCg7ZmRIZTQhfLCyKjIAOYQBT+fDFzvEztHO/7T0Cb390DuU+8ZmIxDiDa17/y0kd+kubmIJf7AG3Xtuaf2sYVXzCf6BPo+Zd6YkBfUtW9arg+xeL0I097jiLNuxWa3m9gGBv7En0VQhTXUOcsR/c3HT+v5TLwq+rwIuYZ3TdDY+3pxKzpU43jLSX1ZoQCgp3K8JpbR43i/+HtLfpNNKkeO77MKlMNZY2mxeKt7gl9xBGaegXno3G5CGGVUMjkEVwVcz4dJioaR8KXV5iotoVRZeevMxaw5i1c8inllTiah6Ff+NPufnIy20E4hOY5zyjmrUOtDmbG2e3CiWEo6UbTPZBMcniZTRiREOLsnmR4zKKldJdm8ld0xVF2VJNQbEig1W8y6KvUKhAyoi1EQFVS2JBbkaZYp2QQ/nJ3trvWzCLWM6DL8vqau+ilAWpTY5BSezPFpgiAmtV8SCzuMs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
